
// Consultaros os usuários cadastrados
#  GET http://localhost:3000/users


// Criar novo usuário
# POST http://localhost:3000/users
# Content-Type: application/json

# {
#   "name": "Maria",
#   "password": "password"
# }


// Requisitar acesso
POST http://localhost:3000/users/login
Content-Type: application/json

{
  "name": "Maria",
  "password": "password"
}